### ISSUE TITLE
Issue with PDF version 1.6

### ISSUE THREAD

**Issue by lobonz** [nbesli/pdf-merger-js#34]
I have an issue with some pdfs, the only difference seems to be the pdf version is 1.6
other files which are version 1.4 merge fine.

Enviroment:
Ubuntu 18.04.5 LTS & Also tested on Windows
Node v10.22.1
pdf-merger-js 3.0.5
pdfjs 2.3.9

`TypeError: Cannot read property 'compressed' of undefined
at parseObject (/home/lifecycle/ouroboro/server/node_modules/pdfjs/lib/object/reference.js:81:15)
at PDFReference.get [as object] (/home/lifecycle/ouroboro/server/node_modules/pdfjs/lib/object/reference.js:15:17)
at new ExternalDocument (/home/lifecycle/ouroboro/server/node_modules/pdfjs/lib/external.js:20:42)
at PDFMerger._addEntireDocument (/home/lifecycle/ouroboro/server/node_modules/pdf-merger-js/index.js:29:15)
at PDFMerger.add (/home/lifecycle/ouroboro/server/node_modules/pdf-merger-js/index.js:11:12)
at router.get (/home/lifecycle/ouroboro/server/src/routes/bom.js:65:20)
at process._tickCallback (internal/process/next_tick.js:68:7) `

The line from bom.js is simply
merger.add(filepath);

[This is a file which causes it to throw the error above](https://www.dropbox.com/s/jsh14kvrzu122cn/8556cb142b350e9742a6c7ab45b7a6d2.pdf?dl=0)

Any advice would be much appreciated

**Comment by lobonz** [comment]
Ok, so seems to be an issue with compressed pdfs rather than the version.
using pdftk to uncompress the same file it then merges fine so think this is likely an issue with the pdfjs library and its handlink of compressed pdfs.
Ill close this as I don't think its an issue with pdf-merger-js although would be good to warn if compressed or something like that.

**Comment by marcomuser** [comment]
I cannot confirm your description of the origin of the error. Several merge tests with compressed PDFs (text or images) ran without problems. And still I have here a scanned PDF (image-based. PDF version 1.3) that spits out exactly the same error as the one you described above. If I re-export this PDF with a different program it merges without problems - no matter whether it is compressed or not.

**Comment by lobonz** [comment]
May be due to the software used, or possibly compression type. I changed to use pdf-lib as I couldn't solve the issue and have hundreds of existing files that wouldn't merge.  All were saved from Acrobat Pro by Extracting single pages.
