### ISSUE TITLE
Error: Expected compressed object stream.This happens in some pdf files.

### ISSUE THREAD

**Issue by yiyinerjin** [nbesli/pdf-merger-js#8]
```
UnhandledPromiseRejectionWarning: Error: Expected compressed object stream
    at parseObject (/Users/linyy/Desktop/project/spider-man-server/node_modules/pdfjs/lib/object/reference.js:88:17)
    at PDFReference.get [as object] (/Users/linyy/Desktop/project/spider-man-server/node_modules/pdfjs/lib/object/reference.js:15:17)
    at new ExternalDocument (/Users/linyy/Desktop/project/spider-man-server/node_modules/pdfjs/lib/external.js:12:42)
    at PDFMerger._addEntireDocument (/Users/linyy/Desktop/project/spider-man-server/node_modules/pdf-merger-js/index.js:33:15)
    at PDFMerger.add (/Users/linyy/Desktop/project/spider-man-server/node_modules/pdf-merger-js/index.js:15:12)
    at /Users/linyy/Desktop/project/spider-man-server/test/baidu.js:8:10
    at Object.<anonymous> (/Users/linyy/Desktop/project/spider-man-server/test/baidu.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
(node:52192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mojoaxel** [comment]
@yiyinerjin can you please provide an example PDF where the error occurs!

**Comment by yiyinerjin** [comment]
@mojoaxel  I send you an email right now. please check it when you are free. thank you!

**Comment by manofaria** [comment]
When merging two pdf files, the resulting file is about twice as large as both files combined, is there a way to keep the resulting merged file to around the same size as the sum of the sizes of the original source files?

**Comment by mojoaxel** [comment]
> When merging two pdf files, the resulting file is about twice as large as both files combined...

@manofaria Please open a new issue for this topic and try to provide two example PDFs. Thx!

**Comment by mojoaxel** [comment]
I'm closing this due to inactivity.
If you encounter this problem please let us know and please provide the problematic pdf files, so we could debug this issue further!
